export 'informacion/informacion_view.dart';
export 'inicio/inicio_view.dart';
export 'juegos/detalle_juego_view.dart';
export 'juegos/lista_juegos_view.dart';
export 'jugadores/jugador_view.dart';
export 'jugadores/lista_jugadores_view.dart';
export 'partidas/detalle_partida_view.dart';
export 'partidas/partidas_view.dart';
export 'acerca_de/acerda_de_view.dart';
